version: "3"

services:

  postgres:
    container_name: postgres-bot
    image: postgres:15.4-bullseye
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_NAME}
      - PGDATA=/var/lib/postgresql/data/pg_data
    ports:
      - ${PG_PORT}:${PG_PORT}
    expose:
      - ${PG_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata


  redis:
    container_name: redis-bot
    image: redis:7.2.0-alpine3.18
    restart: always
    env_file:
      - .env
    ports:
      - ${RD_PORT}:${RD_PORT}
    expose:
      - ${RD_PORT}
    volumes:
      - redis_data:/bitnami/redis/data


  bot:
    container_name: telegram-bot
    build: .
    restart: always
    env_file:
      - .env
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
    external: true
  redis_data:
    external: true
